### ISSUE TITLE
Wrong sub-glen DWI data

### ISSUE THREAD

**Issue by valosekj** [spine-generic/data-single-subject#14]
Whole sub-glen raw DWI data looks atypically - i.) the 1st volume (should be b0) looks similar as b=800 volumes, ii.) one slice in almost all volumes looks like be acquired without diff. weighting:

![sub-glen-raw-dwi](https://user-images.githubusercontent.com/39456460/91643453-a6bf2d80-ea33-11ea-98a0-cad62bb7ea38.gif)

Estimated FA then does not make sense:

<img width="1295" alt="sub-glen-FA" src="https://user-images.githubusercontent.com/39456460/91643459-b474b300-ea33-11ea-8330-62e098ef2e5b.png">

I would exclude sub-glen from DWI analysis.

**Comment by jcohenadad** [comment]
The issue is very likely related to a problem in DICOM to NIFTI conversion. AFAIR the sequence used at that time was non-product, yielding incompatibilities with dcm2niix converter. @alexfoias do we still have the DICOM data?

**Comment by alexfoias** [comment]
I located the raw data, but I cannot open them in fsleyes I have this error. 

![Screen Shot 2020-09-02 at 9 34 47 AM](https://user-images.githubusercontent.com/12564433/91990310-9347e700-ecff-11ea-91ff-7dfc1fa83d7b.png)

Should I upload the data here, maybe one of you can open it ?

**Comment by jcohenadad** [comment]
weird, are there dicom data there? (the folder says "DICOM")

**Comment by alexfoias** [comment]
yes there are. If you want to see the data, you can find them under duke/mri/glen/spine-generic/20171128/DICOM

**Comment by jcohenadad** [comment]
ok i will check. I remember we had a problem with that, and Guillaume Gilbert helped with the conversion.
