### ISSUE TITLE
Cannot download Data

### ISSUE THREAD

**Issue by MounaSah** [spine-generic/data-single-subject#26]
I have downloading the Dataset using this code
 `git clone https://github.com/spine-generic/data-single-subject && \
cd data-single-subject && \
git annex init && \
git annex get`

A new folder data-single-subject was created with all zipped files.
However, when downloading the folder, an error is generated sayin that the archive is either in unknown format or damaged.
Please, how could I download the data on my local machine ?

Thanks for your great effort

**Comment by jcohenadad** [comment]
@MounaSah I cannot reproduce this error. Could you please send us a full copy of your terminal that shows the command line you typed and the output messages (just copy/paste everything)?

**Comment by MounaSah** [comment]
Many thanks for your reply.

The folder containing data-single-subject was well created in my drive content (I'm working on Colab).
I want to export the data on my local machine but an error appeared. Here, you find a screenshot of the error:
![image](https://user-images.githubusercontent.com/90613500/172233407-1b6047da-8da0-48f4-bd4c-c134e632fbab.png)

**Comment by jcohenadad** [comment]
Hi,
What you are pointing to is not the physical file but an alias to the file (since we are using git-annex). Why not downloading the files directly on your machine instead of copying it the way you did it?

**Comment by MounaSah** [comment]
This is what I did; I have downloaded the folder "data-single-subject" directly on my machine. Then, when trying to export the file"sub-chiba750_T2w.nii.gz", I saw the error mentioned above.

**Comment by jcohenadad** [comment]
it’ll be easier for me to help you if you do a screen recording showing exactly what you did and what you are trying to do.

**Comment by MounaSah** [comment]
here you find the code and the log I got
`!git clone https://github.com/spine-generic/data-single-subject && \
!cd data-single-subject && \
!git annex init && \
!git annex get`

Cloning into 'data-single-subject'...
remote: Enumerating objects: 2366, done.
remote: Counting objects: 100% (533/533), done.
remote: Compressing objects: 100% (334/334), done.
remote: Total 2366 (delta 48), reused 380 (delta 47), pack-reused 1833
Receiving objects: 100% (2366/2366), 297.23 KiB | 1.56 MiB/s, done.
Resolving deltas: 100% (571/571), done.
/bin/bash: !cd: command not found

`!gunzip /content/data-single-subject/sub-glen/anat/sub-glen_T2w.nii.gz `

gzip: /content/data-single-subject/sub-glen/anat/sub-glen_T2w.nii.gz: not in gzip format

**Comment by jcohenadad** [comment]
The reason the syntax above does not work is because under google colab, the "\" is not properly interpreted. So, instead, you should do:

~~~
!git clone https://github.com/spine-generic/data-single-subject
!cd data-single-subject
!git annex init
!git annex get
~~~

If it still fails, please copy/paste the output of your terminal.

Also, why are you running 'gunzip' on these data? These are [NIFTI_GZ](https://brainder.org/2012/09/23/the-nifti-file-format/) files, and they can be opened as is with e.g. nibabel (ie: they are not supposed to be unzipped).

**Comment by MounaSah** [comment]
Thank you for your reply
When running the code below I get:
Cloning into 'data-single-subject'...
remote: Enumerating objects: 2366, done.
remote: Counting objects: 100% (533/533), done.
remote: Compressing objects: 100% (334/334), done.
remote: Total 2366 (delta 48), reused 380 (delta 47), pack-reused 1833
Receiving objects: 100% (2366/2366), 297.23 KiB | 1.56 MiB/s, done.
Resolving deltas: 100% (571/571), done.
git: 'annex' is not a git command. See 'git --help'.
git: 'annex' is not a git command. See 'git --help'.

I have installed git and git-annex on my local machine. What should I do on google Colab to have the 'annex' as a git command

**Comment by jcohenadad** [comment]
what if you add a dash:
~~~
!git-annex init
~~~

Also, git-annex should be installed within the colab. See eg: https://colab.research.google.com/github/neuronets/nobrainer/blob/master/guide/inference_with_kwyk_model.ipynb

**Comment by MounaSah** [comment]
Thank you for the link you shared.

I have installed the git-annex on colab. I've checked the version:

`!git-annex version`

git-annex version: 10.20220322-1~ndall+1
build flags: Assistant Webapp Pairing Inotify DBus DesktopNotify TorrentParser MagicMime Feeds Testsuite S3 WebDAV
dependency versions: aws-0.22 bloomfilter-2.0.1.0 cryptonite-0.26 DAV-1.3.4 feed-1.3.0.1 ghc-8.8.4 http-client-0.6.4.1 persistent-sqlite-2.10.6.2 torrent-10000.1.1 uuid-1.3.13 yesod-1.6.1.0
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2BP512E BLAKE2BP512 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL X*
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs httpalso borg hook external
operating system: linux x86_64
supported repository versions: 8 9 10
upgrade supported from repository versions: 0 1 2 3 4 5 6 7 8 9 10

`!git clone https://github.com/spine-generic/data-single-subject
!cd data-single-subject
!git-annex init
!git-annex get`

but it still fails :(

fatal: destination path 'data-single-subject' already exists and is not an empty directory.
git-annex: Not in a git repository.
git-annex: Not in a git repository.

**Comment by jcohenadad** [comment]
~~~
fatal: destination path 'data-single-subject' already exists and is not an empty directory.
~~~

you need to remove this repository first.

**Comment by MounaSah** [comment]
Sorry for the disturbance
Could you please redirect me how to move from version 10 to version 8 of git-annex ?

**Comment by jcohenadad** [comment]
@MounaSah have you seen this: https://github.com/spine-generic/data-single-subject/issues/26#issuecomment-1150130314

could you please fix this before, then re-run every line, copy/paste everything, and then i'll follow up

please: it is VERY important that you copy/paste all your input/output otherwise i cannot properly help you

**Comment by mguaypaq** [comment]
Closing due to no response in the past 4 months.
