### ISSUE TITLE
Processing issues in r20200826 release

### ISSUE THREAD

**Issue by valosekj** [spine-generic/data-single-subject#3]
I found following processing issues in [r20200826](https://github.com/spine-generic/data-single-subject/releases/tag/r20200826) release.

**GM to correct:**

`sub-juntendoAchieva_T2star_rms.nii.gz`
<img width="949" alt="image" src="https://user-images.githubusercontent.com/39456460/91974886-2f391900-ed27-11ea-8781-4b5abba1260e.png">

`sub-perform_T2star_rms.nii.gz`
<img width="948" alt="image" src="https://user-images.githubusercontent.com/39456460/91975005-63143e80-ed27-11ea-92f8-3945295ff4e0.png">

`sub-glen_T2star_rms.nii.gz`
<img width="949" alt="image" src="https://user-images.githubusercontent.com/39456460/91975064-7b845900-ed27-11ea-97a2-ab80c80e9877.png">

`sub-tokyoSkyra_T2star_rms.nii.gz`
<img width="946" alt="image" src="https://user-images.githubusercontent.com/39456460/91975130-935bdd00-ed27-11ea-9fd4-12500d145537.png">

`sub-unf_T2star_rms.nii.gz`
<img width="949" alt="image" src="https://user-images.githubusercontent.com/39456460/91975192-b1294200-ed27-11ea-8c3d-a5e46a3ff068.png">

**Comment by jcohenadad** [comment]
Fixed
